---
version: '2'
services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:6.1.1
    ports:
    - 8082:8082
    hostname: rest-proxy
    container_name: kafka-rest-proxy
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: pkc-ep9mm.us-east-2.aws.confluent.cloud:9092
      KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule
        required username="R32OO3FH3HVWKK5C" password="hfB81DKUnN12cjbHKAUKsPEP5/xqGdx1ORe/PTE4qeDnoSZ2oQaO6P8rR1pRUqdq";
      KAFKA_REST_PRODUCER_ACKS: '1'
      KAFKA_REST_ADMIN_REQUEST_TIMEOUT_MS: '50000'
      KAFKA_REST_SASL_MECHANISM: PLAIN
      KAFKA_REST_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule
        required username="R32OO3FH3HVWKK5C" password="hfB81DKUnN12cjbHKAUKsPEP5/xqGdx1ORe/PTE4qeDnoSZ2oQaO6P8rR1pRUqdq";
      KAFKA_REST_CLIENT_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: 4XYJA5FT52ZOJZR4:cpZF2xmzaOesySYKa3vtpGDohfYdR/GgYhqxHqvu5R8JwDGGOgKM6kuECWqf7Eac
      KAFKA_REST_CLIENT_SASL_MECHANISM: PLAIN
      KAFKA_REST_SCHEMA_REGISTRY_URL: https://psrc-4xgzx.us-east-2.aws.confluent.cloud
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: '25000'
      KAFKA_REST_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      KAFKA_REST_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_REST_CONSUMER_RETRY_BACKOFF_MS: '600'
      KAFKA_REST_CLIENT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_REST_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS: pkc-ep9mm.us-east-2.aws.confluent.cloud:9092