CREATE STREAM PAGEME WITH (KAFKA_TOPIC='pageme', PARTITIONS=1, REPLICAS=3, WRAP_SINGLE_VALUE=false) AS SELECT 
(CASE 
WHEN (ABS(GARAGE.`Z value`) < 30) THEN 'To=%2BZZZZZZZZZZZZ&MessagingServiceSid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&Body=Garage%20door%20is%20now%20closed' 
WHEN (ABS(GARAGE.`Z value`) > 500) THEN 'To=%2BZZZZZZZZZZZ&MessagingServiceSid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&Body=Garage%20door%20is%20now%20open' 
END) MESSAGE
FROM GARAGE
EMIT CHANGES;
